/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Budget
 */
export interface Budget {
    /**
     * 
     * @type {number}
     * @memberof Budget
     */
    amountInCents?: number;
    /**
     * 
     * @type {number}
     * @memberof Budget
     */
    categoryId?: number;
    /**
     * 
     * @type {Date}
     * @memberof Budget
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof Budget
     */
    activityType?: number;
    /**
     * 
     * @type {number}
     * @memberof Budget
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof Budget
     */
    predictedTotal?: number;
    /**
     * 
     * @type {string}
     * @memberof Budget
     */
    percentage?: string;
}

/**
 * Check if a given object implements the Budget interface.
 */
export function instanceOfBudget(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BudgetFromJSON(json: any): Budget {
    return BudgetFromJSONTyped(json, false);
}

export function BudgetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Budget {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amountInCents': !exists(json, 'amount_in_cents') ? undefined : json['amount_in_cents'],
        'categoryId': !exists(json, 'category_id') ? undefined : json['category_id'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'activityType': !exists(json, 'activity_type') ? undefined : json['activity_type'],
        'total': !exists(json, 'total') ? undefined : json['total'],
        'predictedTotal': !exists(json, 'predicted_total') ? undefined : json['predicted_total'],
        'percentage': !exists(json, 'percentage') ? undefined : json['percentage'],
    };
}

export function BudgetToJSON(value?: Budget | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount_in_cents': value.amountInCents,
        'category_id': value.categoryId,
        'date': value.date === undefined ? undefined : (value.date.toISOString().substr(0,10)),
        'activity_type': value.activityType,
        'total': value.total,
        'predicted_total': value.predictedTotal,
        'percentage': value.percentage,
    };
}

