/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    InstallmentTransaction,
    instanceOfInstallmentTransaction,
    InstallmentTransactionFromJSON,
    InstallmentTransactionFromJSONTyped,
    InstallmentTransactionToJSON,
} from './InstallmentTransaction';
import {
    RecurringTransaction,
    instanceOfRecurringTransaction,
    RecurringTransactionFromJSON,
    RecurringTransactionFromJSONTyped,
    RecurringTransactionToJSON,
} from './RecurringTransaction';
import {
    Transaction,
    instanceOfTransaction,
    TransactionFromJSON,
    TransactionFromJSONTyped,
    TransactionToJSON,
} from './Transaction';

/**
 * @type CreateTransactionRequest
 * 
 * @export
 */
export type CreateTransactionRequest = InstallmentTransaction | RecurringTransaction | Transaction;

export function CreateTransactionRequestFromJSON(json: any): CreateTransactionRequest {
    return CreateTransactionRequestFromJSONTyped(json, false);
}

export function CreateTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTransactionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...InstallmentTransactionFromJSONTyped(json, true), ...RecurringTransactionFromJSONTyped(json, true), ...TransactionFromJSONTyped(json, true) };
}

export function CreateTransactionRequestToJSON(value?: CreateTransactionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfInstallmentTransaction(value)) {
        return InstallmentTransactionToJSON(value as InstallmentTransaction);
    }
    if (instanceOfRecurringTransaction(value)) {
        return RecurringTransactionToJSON(value as RecurringTransaction);
    }
    if (instanceOfTransaction(value)) {
        return TransactionToJSON(value as Transaction);
    }

    return {};
}

