/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreditCardInvoice
 */
export interface CreditCardInvoice {
    /**
     * 
     * @type {number}
     * @memberof CreditCardInvoice
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof CreditCardInvoice
     */
    date?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreditCardInvoice
     */
    startingDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreditCardInvoice
     */
    closingDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof CreditCardInvoice
     */
    amountCents?: number;
    /**
     * 
     * @type {number}
     * @memberof CreditCardInvoice
     */
    paymentAmountCents?: number;
    /**
     * 
     * @type {number}
     * @memberof CreditCardInvoice
     */
    balanceCents?: number;
    /**
     * 
     * @type {number}
     * @memberof CreditCardInvoice
     */
    previousBalanceCents?: number;
    /**
     * 
     * @type {number}
     * @memberof CreditCardInvoice
     */
    creditCardId?: number;
}

/**
 * Check if a given object implements the CreditCardInvoice interface.
 */
export function instanceOfCreditCardInvoice(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreditCardInvoiceFromJSON(json: any): CreditCardInvoice {
    return CreditCardInvoiceFromJSONTyped(json, false);
}

export function CreditCardInvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditCardInvoice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'startingDate': !exists(json, 'starting_date') ? undefined : (new Date(json['starting_date'])),
        'closingDate': !exists(json, 'closing_date') ? undefined : (new Date(json['closing_date'])),
        'amountCents': !exists(json, 'amount_cents') ? undefined : json['amount_cents'],
        'paymentAmountCents': !exists(json, 'payment_amount_cents') ? undefined : json['payment_amount_cents'],
        'balanceCents': !exists(json, 'balance_cents') ? undefined : json['balance_cents'],
        'previousBalanceCents': !exists(json, 'previous_balance_cents') ? undefined : json['previous_balance_cents'],
        'creditCardId': !exists(json, 'credit_card_id') ? undefined : json['credit_card_id'],
    };
}

export function CreditCardInvoiceToJSON(value?: CreditCardInvoice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'date': value.date === undefined ? undefined : (value.date.toISOString().substr(0,10)),
        'starting_date': value.startingDate === undefined ? undefined : (value.startingDate.toISOString().substr(0,10)),
        'closing_date': value.closingDate === undefined ? undefined : (value.closingDate.toISOString().substr(0,10)),
        'amount_cents': value.amountCents,
        'payment_amount_cents': value.paymentAmountCents,
        'balance_cents': value.balanceCents,
        'previous_balance_cents': value.previousBalanceCents,
        'credit_card_id': value.creditCardId,
    };
}

