/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Failed Authentication
 * @export
 * @interface FailedAuthentication
 */
export interface FailedAuthentication {
    /**
     * 
     * @type {string}
     * @memberof FailedAuthentication
     */
    error?: FailedAuthenticationErrorEnum;
}

/**
* @export
* @enum {string}
*/
export enum FailedAuthenticationErrorEnum {
    NoAutorizado = 'Não autorizado'
}


/**
 * Check if a given object implements the FailedAuthentication interface.
 */
export function instanceOfFailedAuthentication(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FailedAuthenticationFromJSON(json: any): FailedAuthentication {
    return FailedAuthenticationFromJSONTyped(json, false);
}

export function FailedAuthenticationFromJSONTyped(json: any, ignoreDiscriminator: boolean): FailedAuthentication {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function FailedAuthenticationToJSON(value?: FailedAuthentication | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
    };
}

