/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InstallmentTransactionAllOfInstallmentsAttributes } from './InstallmentTransactionAllOfInstallmentsAttributes';
import {
    InstallmentTransactionAllOfInstallmentsAttributesFromJSON,
    InstallmentTransactionAllOfInstallmentsAttributesFromJSONTyped,
    InstallmentTransactionAllOfInstallmentsAttributesToJSON,
} from './InstallmentTransactionAllOfInstallmentsAttributes';

/**
 * Installment Transaction
 * @export
 * @interface InstallmentTransaction
 */
export interface InstallmentTransaction {
    /**
     * ID of the Bank Account
     * @type {number}
     * @memberof InstallmentTransaction
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InstallmentTransaction
     */
    description: string;
    /**
     * 
     * @type {Date}
     * @memberof InstallmentTransaction
     */
    date: Date;
    /**
     * 
     * @type {boolean}
     * @memberof InstallmentTransaction
     */
    paid?: boolean;
    /**
     * 
     * @type {number}
     * @memberof InstallmentTransaction
     */
    amountCents?: number;
    /**
     * 
     * @type {number}
     * @memberof InstallmentTransaction
     */
    totalInstallments?: number;
    /**
     * 
     * @type {number}
     * @memberof InstallmentTransaction
     */
    installment?: number;
    /**
     * 
     * @type {boolean}
     * @memberof InstallmentTransaction
     */
    recurring?: boolean;
    /**
     * ID of the Bank Account
     * @type {number}
     * @memberof InstallmentTransaction
     */
    accountId?: number;
    /**
     * 
     * @type {string}
     * @memberof InstallmentTransaction
     */
    accountType?: InstallmentTransactionAccountTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof InstallmentTransaction
     */
    categoryId?: number;
    /**
     * 
     * @type {string}
     * @memberof InstallmentTransaction
     */
    notes: string | null;
    /**
     * 
     * @type {number}
     * @memberof InstallmentTransaction
     */
    attachmentsCount?: number;
    /**
     * 
     * @type {number}
     * @memberof InstallmentTransaction
     */
    creditCardId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof InstallmentTransaction
     */
    creditCardInvoiceId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof InstallmentTransaction
     */
    paidCreditCardId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof InstallmentTransaction
     */
    paidCreditCardInvoiceId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof InstallmentTransaction
     */
    opositeTransactionId?: number | null;
    /**
     * ID of the Bank Account
     * @type {number}
     * @memberof InstallmentTransaction
     */
    opositeAccountId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InstallmentTransaction
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof InstallmentTransaction
     */
    updatedAt?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof InstallmentTransaction
     */
    tags?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof InstallmentTransaction
     */
    attachments?: Array<string>;
    /**
     * 
     * @type {InstallmentTransactionAllOfInstallmentsAttributes}
     * @memberof InstallmentTransaction
     */
    installmentsAttributes?: InstallmentTransactionAllOfInstallmentsAttributes;
}

/**
* @export
* @enum {string}
*/
export enum InstallmentTransactionAccountTypeEnum {
    Account = 'Account',
    CreditCard = 'CreditCard'
}


/**
 * Check if a given object implements the InstallmentTransaction interface.
 */
export function instanceOfInstallmentTransaction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "notes" in value;

    return isInstance;
}

export function InstallmentTransactionFromJSON(json: any): InstallmentTransaction {
    return InstallmentTransactionFromJSONTyped(json, false);
}

export function InstallmentTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstallmentTransaction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'description': json['description'],
        'date': (new Date(json['date'])),
        'paid': !exists(json, 'paid') ? undefined : json['paid'],
        'amountCents': !exists(json, 'amount_cents') ? undefined : json['amount_cents'],
        'totalInstallments': !exists(json, 'total_installments') ? undefined : json['total_installments'],
        'installment': !exists(json, 'installment') ? undefined : json['installment'],
        'recurring': !exists(json, 'recurring') ? undefined : json['recurring'],
        'accountId': !exists(json, 'account_id') ? undefined : json['account_id'],
        'accountType': !exists(json, 'account_type') ? undefined : json['account_type'],
        'categoryId': !exists(json, 'category_id') ? undefined : json['category_id'],
        'notes': json['notes'],
        'attachmentsCount': !exists(json, 'attachments_count') ? undefined : json['attachments_count'],
        'creditCardId': !exists(json, 'credit_card_id') ? undefined : json['credit_card_id'],
        'creditCardInvoiceId': !exists(json, 'credit_card_invoice_id') ? undefined : json['credit_card_invoice_id'],
        'paidCreditCardId': !exists(json, 'paid_credit_card_id') ? undefined : json['paid_credit_card_id'],
        'paidCreditCardInvoiceId': !exists(json, 'paid_credit_card_invoice_id') ? undefined : json['paid_credit_card_invoice_id'],
        'opositeTransactionId': !exists(json, 'oposite_transaction_id') ? undefined : json['oposite_transaction_id'],
        'opositeAccountId': !exists(json, 'oposite_account_id') ? undefined : json['oposite_account_id'],
        'createdAt': !exists(json, 'created_at') ? undefined : json['created_at'],
        'updatedAt': !exists(json, 'updated_at') ? undefined : json['updated_at'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'attachments': !exists(json, 'attachments') ? undefined : json['attachments'],
        'installmentsAttributes': !exists(json, 'installments_attributes') ? undefined : InstallmentTransactionAllOfInstallmentsAttributesFromJSON(json['installments_attributes']),
    };
}

export function InstallmentTransactionToJSON(value?: InstallmentTransaction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'description': value.description,
        'date': (value.date.toISOString().substr(0,10)),
        'paid': value.paid,
        'amount_cents': value.amountCents,
        'total_installments': value.totalInstallments,
        'installment': value.installment,
        'recurring': value.recurring,
        'account_id': value.accountId,
        'account_type': value.accountType,
        'category_id': value.categoryId,
        'notes': value.notes,
        'attachments_count': value.attachmentsCount,
        'credit_card_id': value.creditCardId,
        'credit_card_invoice_id': value.creditCardInvoiceId,
        'paid_credit_card_id': value.paidCreditCardId,
        'paid_credit_card_invoice_id': value.paidCreditCardInvoiceId,
        'oposite_transaction_id': value.opositeTransactionId,
        'oposite_account_id': value.opositeAccountId,
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
        'tags': value.tags,
        'attachments': value.attachments,
        'installments_attributes': InstallmentTransactionAllOfInstallmentsAttributesToJSON(value.installmentsAttributes),
    };
}

