/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InstallmentTransactionAllOfInstallmentsAttributes } from './InstallmentTransactionAllOfInstallmentsAttributes';
import {
    InstallmentTransactionAllOfInstallmentsAttributesFromJSON,
    InstallmentTransactionAllOfInstallmentsAttributesFromJSONTyped,
    InstallmentTransactionAllOfInstallmentsAttributesToJSON,
} from './InstallmentTransactionAllOfInstallmentsAttributes';

/**
 * 
 * @export
 * @interface InstallmentTransactionAllOf
 */
export interface InstallmentTransactionAllOf {
    /**
     * 
     * @type {InstallmentTransactionAllOfInstallmentsAttributes}
     * @memberof InstallmentTransactionAllOf
     */
    installmentsAttributes?: InstallmentTransactionAllOfInstallmentsAttributes;
}

/**
 * Check if a given object implements the InstallmentTransactionAllOf interface.
 */
export function instanceOfInstallmentTransactionAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InstallmentTransactionAllOfFromJSON(json: any): InstallmentTransactionAllOf {
    return InstallmentTransactionAllOfFromJSONTyped(json, false);
}

export function InstallmentTransactionAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstallmentTransactionAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'installmentsAttributes': !exists(json, 'installments_attributes') ? undefined : InstallmentTransactionAllOfInstallmentsAttributesFromJSON(json['installments_attributes']),
    };
}

export function InstallmentTransactionAllOfToJSON(value?: InstallmentTransactionAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'installments_attributes': InstallmentTransactionAllOfInstallmentsAttributesToJSON(value.installmentsAttributes),
    };
}

