/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstallmentTransactionAllOfInstallmentsAttributes
 */
export interface InstallmentTransactionAllOfInstallmentsAttributes {
    /**
     * 
     * @type {number}
     * @memberof InstallmentTransactionAllOfInstallmentsAttributes
     */
    total: number;
    /**
     * 
     * @type {string}
     * @memberof InstallmentTransactionAllOfInstallmentsAttributes
     */
    periodicity: InstallmentTransactionAllOfInstallmentsAttributesPeriodicityEnum;
}

/**
* @export
* @enum {string}
*/
export enum InstallmentTransactionAllOfInstallmentsAttributesPeriodicityEnum {
    Monthly = 'monthly',
    Yearly = 'yearly',
    Weekly = 'weekly',
    Biweekly = 'biweekly',
    Bimonthly = 'bimonthly',
    Trimonthly = 'trimonthly'
}


/**
 * Check if a given object implements the InstallmentTransactionAllOfInstallmentsAttributes interface.
 */
export function instanceOfInstallmentTransactionAllOfInstallmentsAttributes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "total" in value;
    isInstance = isInstance && "periodicity" in value;

    return isInstance;
}

export function InstallmentTransactionAllOfInstallmentsAttributesFromJSON(json: any): InstallmentTransactionAllOfInstallmentsAttributes {
    return InstallmentTransactionAllOfInstallmentsAttributesFromJSONTyped(json, false);
}

export function InstallmentTransactionAllOfInstallmentsAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstallmentTransactionAllOfInstallmentsAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'total': json['total'],
        'periodicity': json['periodicity'],
    };
}

export function InstallmentTransactionAllOfInstallmentsAttributesToJSON(value?: InstallmentTransactionAllOfInstallmentsAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total': value.total,
        'periodicity': value.periodicity,
    };
}

