/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotFound
 */
export interface NotFound {
    /**
     * 
     * @type {string}
     * @memberof NotFound
     */
    error?: NotFoundErrorEnum;
}

/**
* @export
* @enum {string}
*/
export enum NotFoundErrorEnum {
    RegistroNoEncontrado = 'registro não encontrado'
}


/**
 * Check if a given object implements the NotFound interface.
 */
export function instanceOfNotFound(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NotFoundFromJSON(json: any): NotFound {
    return NotFoundFromJSONTyped(json, false);
}

export function NotFoundFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotFound {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function NotFoundToJSON(value?: NotFound | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
    };
}

