/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecurringTransactionAllOfRecurrenceAttributes
 */
export interface RecurringTransactionAllOfRecurrenceAttributes {
    /**
     * 
     * @type {string}
     * @memberof RecurringTransactionAllOfRecurrenceAttributes
     */
    periodicity: RecurringTransactionAllOfRecurrenceAttributesPeriodicityEnum;
}

/**
* @export
* @enum {string}
*/
export enum RecurringTransactionAllOfRecurrenceAttributesPeriodicityEnum {
    Monthly = 'monthly',
    Yearly = 'yearly',
    Weekly = 'weekly',
    Biweekly = 'biweekly',
    Bimonthly = 'bimonthly',
    Trimonthly = 'trimonthly'
}


/**
 * Check if a given object implements the RecurringTransactionAllOfRecurrenceAttributes interface.
 */
export function instanceOfRecurringTransactionAllOfRecurrenceAttributes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "periodicity" in value;

    return isInstance;
}

export function RecurringTransactionAllOfRecurrenceAttributesFromJSON(json: any): RecurringTransactionAllOfRecurrenceAttributes {
    return RecurringTransactionAllOfRecurrenceAttributesFromJSONTyped(json, false);
}

export function RecurringTransactionAllOfRecurrenceAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurringTransactionAllOfRecurrenceAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'periodicity': json['periodicity'],
    };
}

export function RecurringTransactionAllOfRecurrenceAttributesToJSON(value?: RecurringTransactionAllOfRecurrenceAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'periodicity': value.periodicity,
    };
}

