/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RecurringTransactionAllOfRecurrenceAttributes } from './RecurringTransactionAllOfRecurrenceAttributes';
import {
    RecurringTransactionAllOfRecurrenceAttributesFromJSON,
    RecurringTransactionAllOfRecurrenceAttributesFromJSONTyped,
    RecurringTransactionAllOfRecurrenceAttributesToJSON,
} from './RecurringTransactionAllOfRecurrenceAttributes';

/**
 * 
 * @export
 * @interface RecurringTransactionAllOf
 */
export interface RecurringTransactionAllOf {
    /**
     * 
     * @type {RecurringTransactionAllOfRecurrenceAttributes}
     * @memberof RecurringTransactionAllOf
     */
    recurrenceAttributes: RecurringTransactionAllOfRecurrenceAttributes;
}

/**
 * Check if a given object implements the RecurringTransactionAllOf interface.
 */
export function instanceOfRecurringTransactionAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "recurrenceAttributes" in value;

    return isInstance;
}

export function RecurringTransactionAllOfFromJSON(json: any): RecurringTransactionAllOf {
    return RecurringTransactionAllOfFromJSONTyped(json, false);
}

export function RecurringTransactionAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurringTransactionAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recurrenceAttributes': RecurringTransactionAllOfRecurrenceAttributesFromJSON(json['recurrence_attributes']),
    };
}

export function RecurringTransactionAllOfToJSON(value?: RecurringTransactionAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'recurrence_attributes': RecurringTransactionAllOfRecurrenceAttributesToJSON(value.recurrenceAttributes),
    };
}

