/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTransactionRequestAllOf
 */
export interface UpdateTransactionRequestAllOf {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateTransactionRequestAllOf
     */
    updateFuture?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateTransactionRequestAllOf
     */
    updateAll?: boolean;
}

/**
 * Check if a given object implements the UpdateTransactionRequestAllOf interface.
 */
export function instanceOfUpdateTransactionRequestAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateTransactionRequestAllOfFromJSON(json: any): UpdateTransactionRequestAllOf {
    return UpdateTransactionRequestAllOfFromJSONTyped(json, false);
}

export function UpdateTransactionRequestAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTransactionRequestAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'updateFuture': !exists(json, 'update_future') ? undefined : json['update_future'],
        'updateAll': !exists(json, 'update_all') ? undefined : json['update_all'],
    };
}

export function UpdateTransactionRequestAllOfToJSON(value?: UpdateTransactionRequestAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'update_future': value.updateFuture,
        'update_all': value.updateAll,
    };
}

