name: NPM Publish
on:
  push:
    branches:
      - main
    paths:
      - clients/typescript/package.json
jobs:
  npm-publish:
    name: Generate Typescript Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
      - name: Install packages
        working-directory: clients/typescript
        run: npm ci
      - name: Publish to NPM
        working-directory: clients/typescript
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
